server:
  port: 8002

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver        #mysql驱动包
   # url: jdbc:mysql://localhost:3306/db2019?serverTimezone=GMT%2B8
   # username: root
  # password: 123456
    url: jdbc:mysql://124.70.160.99:3305/db2019?serverTimezone=GMT%2B8
    username: root
    password: _Yjyw!bEg1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luhuihahaha.com.luhuihahaha.com.luhuihahaha.springcloud.entities       #所有Entity别名类所在包

eureka:
  client:
    #表示是否讲自己注册进入eurekaServer默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #集群版
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:700/eureka/
      #单机版
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true