server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: cloud-order-hystrix-service

feign:
  hystrix:
    enabled: true